# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactImportSampleProject' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactImportSampleProject

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket’,
    'RCTImage', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

end
